### ISSUE TITLE
棒読みボタンが表示されない

### ISSUE THREAD

**Issue by gtk2k** [beraboume/nicolive.berabou.me#14]
棒読みボタン消しました？

**Comment by 59naga** [comment]
![2015-10-06 22 35 56](https://cloud.githubusercontent.com/assets/1548478/10310005/9f855c10-6c7a-11e5-8aa0-9d0d5ce3330e.png)

OSX 10.11+ Google Chrome 45.0.2454.93ではこのように表示されていますね。
２つあったボタンのうち、`fork me on github`ボタンを削除しています。

**Comment by gtk2k** [comment]
なるほど、了解です。
