### ISSUE TITLE
「サーバーへ接続」ダイアログで正しいセッションIDに対してもバリデーションエラーが起きる

### ISSUE THREAD

**Issue by endaaman** [beraboume/nicolive.berabou.me#18]
日本語で失礼します。

https://github.com/59naga/nicolive.berabou.me/blob/master/root/view.jade#L15

この行なんですが、おそらくニコニコ動画のアカウントIDが6桁の場合でしかバリデーションが通りません。サブアカウントがあればそれを使って確認してみてください。PRにしようかとも思ったんですが上手く環境が作れなかったのでissueで報告だけさせていただきます。

**Comment by 59naga** [comment]
ありがとうございます。

確かに84文字でない場合バリデーションエラーでフォームが送信できないのを確認できました。
このコミットでpattern属性の84文字制限を削除しています。
